---
- name: ALT_DISK on AIX
  hosts: "{{host_name}}"
  gather_facts: false
  vars:
    host_name: alttest
    targets: hdisk1

  tasks:
    - name: Perform an alternate disk copy of the rootvg to hdisk3
      ibm.power_aix.alt_disk:
        action: copy
        targets: hdisk3
        force: true

    - name: Perform an alternate disk copy of the rootvg to the nearest disk that can be selected
      ibm.power_aix.alt_disk:
        action: copy
        disk_size_policy: nearest
        allow_old_rootvg: true
        force: true

    - name: Perform an alternate disk copy of the rootvg to the smallest disk that can be selected
      ibm.power_aix.alt_disk:
        action: copy
        disk_size_policy: minimize

    - name: Perform a cleanup of any existing alternate disk copy
      ibm.power_aix.alt_disk:
        action: clean

    - name: Perform a cleanup of any existing alternate disk copy and old rootvg
      ibm.power_aix.alt_disk:
        action: clean
        allow_old_rootvg: true

    - name: Perform an alternate disk wakeup of the rootvg to hdisk3
      ibm.power_aix.alt_disk:
        action: wakeup
        targets: hdisk3
    - name: Perform an alternate disk sleep of the rootvg
      ibm.power_aix.alt_disk:
        action: sleep
        rebuild_boot_image: true
