---
- name: Check if NIM master fileset is present on "{{ nim_master_migration_master_b }}"
  ansible.builtin.stat:
    path: "{{ nim_master_migration_nim_master_fileset_dest }}"
  register: nim_master_migration_master_fileset
  delegate_to: "{{ nim_master_migration_master_b }}"

- name: If NIM master fileset does not exist, run the following tasks
  when: not nim_master_migration_master_fileset.stat.exists
  block:
    - name: Copy NIM master fileset to "{{ nim_master_migration_master_b }}"
      ansible.builtin.copy:
        src: "{{ nim_master_migration_nim_master_fileset_src }}"
        dest: "{{ nim_master_migration_nim_master_fileset_dest }}"
        mode: '0777'
      delegate_to: "{{ nim_master_migration_master_b }}"
    - name: Check if file has been moved
      ansible.builtin.stat:
        path: "{{ nim_master_migration_nim_master_fileset_dest }}"
      delegate_to: "{{ nim_master_migration_master_b }}"
      register: nim_master_migration_file_present

    - name: Fail if transfer was not successful
      ansible.builtin.fail:
        msg: File could not be copied to "{{ nim_master_migration_master_b }}"
      when: not nim_master_migration_file_present.stat.exists
